export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const CREATE_NEW_USER_REQUEST = "CREATE_NEW_USER_REQUEST";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAIL = "CREATE_NEW_USER_FAIL";

export const CREATE_LOGIN_REQUEST = "CREATE_LOGIN_REQUEST";
export const CREATE_LOGIN_SUCCESS = "CREATE_LOGIN_SUCCESS";
export const CREATE_LOGIN_FAIL = "CREATE_LOGIN_FAIL";